export const ALL_CARD_LIST_REQUEST = 'ALL_CARD_LIST_REQUEST'
export const ALL_CARD_LIST_SUCCESS = 'ALL_CARD_LIST_SUCCESS'
export const ALL_CARD_LIST_FAIL = 'ALL_CARD_LIST_FAIL'

export const CARD_DETAIL_REQUEST = 'CARD_DETAIL_REQUEST'
export const CARD_DETAIL_SUCCESS = 'CARD_DETAIL_SUCCESS'
export const CARD_DETAIL_FAIL = 'CARD_DETAIL_FAIL'

export const GET_RATES_REQUEST = 'GET_RATES_REQUEST'
export const GET_RATES_SUCCESS = 'GET_RATES_SUCCESS'
export const GET_RATES_FAIL = 'GET_RATES_FAIL'

export const CARD_CHECK_PIN_REQUEST = 'CARD_CHECK_PIN_REQUEST'
export const CARD_CHECK_PIN_SUCCESS = 'CARD_CHECK_PIN_SUCCESS'
export const CARD_CHECK_PIN_FAIL = 'CARD_CHECK_PIN_FAIL'
export const CARD_CHECK_PIN_RESET = 'CARD_CHECK_PIN_RESET'

export const CARD_CHECK_CCV_REQUEST = 'CARD_CHECK_CCV_REQUEST'
export const CARD_CHECK_CCV_SUCCESS = 'CARD_CHECK_CCV_SUCCESS'
export const CARD_CHECK_CCV_FAIL = 'CARD_CHECK_CCV_FAIL'
export const CARD_CHECK_CCV_RESET = 'CARD_CHECK_CCV_RESET'

export const CARD_CREATE_REQUEST = 'CARD_CREATE_REQUEST'
export const CARD_CREATE_SUCCESS = 'CARD_CREATE_SUCCESS'
export const CARD_CREATE_FAIL = 'CARD_CREATE_FAIL'
export const CARD_CREATE_RESET = 'CARD_CREATE_RESET'

export const GET_ALL_CARD_LEFT_REQUEST = 'GET_ALL_CARD_LEFT_REQUEST'
export const GET_ALL_CARD_LEFT_SUCCESS = 'GET_ALL_CARD_LEFT_SUCCESS'
export const GET_ALL_CARD_LEFT_FAIL = 'GET_ALL_CARD_LEFT_FAIL'

export const GET_CARD_LEFT_REQUEST = 'GET_CARD_LEFT_REQUEST'
export const GET_CARD_LEFT_SUCCESS = 'GET_CARD_LEFT_SUCCESS'
export const GET_CARD_LEFT_FAIL = 'GET_CARD_LEFT_FAIL'

export const GENERATE_CARD_REQUEST = 'GENERATE_CARD_REQUEST'
export const GENERATE_CARD_SUCCESS = 'GENERATE_CARD_SUCCESS'
export const GENERATE_CARD_FAIL = 'GENERATE_CARD_FAIL'
export const GENERATE_CARD_RESET = 'GENERATE_CARD_RESET'







