export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'
export const USER_REGISTER_RESET = 'USER_REGISTER_FAIL'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'

export const USER_UPDATE_PASSWORD_REQUEST = 'USER_UPDATE_PASSWORD_REQUEST'
export const USER_UPDATE_PASSWORD_SUCCESS = 'USER_UPDATE_PASSWORD_SUCCESS'
export const USER_UPDATE_PASSWORD_FAIL = 'USER_UPDATE_PASSWORD_FAIL'
export const USER_UPDATE_PASSWORD_RESET = 'USER_UPDATE_PASSWORD_RESET'

export const USER_VIEW_ALL_CARD_REQUEST = 'USER_VIEW_ALL_CARD_REQUEST'
export const USER_VIEW_ALL_CARD_SUCCESS = 'USER_VIEW_ALL_CARD_SUCCESS'
export const USER_VIEW_ALL_CARD_FAIL = 'USER_VIEW_ALL_CARD_FAIL'


export const USER_VIEW_MY_CARD_DETAIL_FAIL = 'USER_VIEW_MY_CARD_DETAIL_FAIL'
export const USER_VIEW_MY_CARD_DETAIL_REQUEST = 'USER_VIEW_MY_CARD_DETAIL_REQUEST'
export const USER_VIEW_MY_CARD_DETAIL_SUCCESS = 'USER_VIEW_MY_CARD_DETAIL_SUCCESS'

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'
export const USER_LIST_RESET = 'USER_LIST_RESET'

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL'
export const USER_DELETE_RESET = 'USER_DELETE_RESET'

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET'

export const USER_ADD_MONEY_REQUEST = 'USER_ADD_MONEY_REQUEST'
export const USER_ADD_MONEY_SUCCESS = 'USER_ADD_MONEY_SUCCESS'
export const USER_ADD_MONEY_FAIL = 'USER_ADD_MONEY_FAIL'

export const USER_TRANSFER_REQUEST = 'USER_TRANSFER_REQUEST'
export const USER_TRANSFER_SUCCESS = 'USER_TRANSFER_SUCCESS'
export const USER_TRANSFER_FAIL = 'USER_TRANSFER_FAIL'

export const USER_WITHDRAW_REQUEST = 'USER_WITHDRAW_REQUEST'
export const USER_WITHDRAW_FAIL = 'USER_WITHDRAW_FAIL'
export const USER_WITHDRAW_SUCCESS = 'USER_WITHDRAW_SUCCESS'
export const USER_WITHDRAW_RESET = 'USER_WITHDRAW_RESET'

export const USER_VIEW_MY_LOG_REQUEST = 'USER_VIEW_MY_LOG_REQUEST'
export const USER_VIEW_MY_LOG_SUCCESS = 'USER_VIEW_MY_LOG_SUCCESS'
export const USER_VIEW_MY_LOG_FAIL = 'USER_VIEW_MY_LOG_FAIL'
export const USER_VIEW_MY_LOG_RESET = 'USER_VIEW_MY_LOG_RESET'

export const USER_REGISTER_CARD_REQUEST = 'USER_REGISTER_CARD_REQUEST'
export const USER_REGISTER_CARD_SUCCESS = 'USER_REGISTER_CARD_SUCCESS'
export const USER_REGISTER_CARD_FAIL = 'USER_REGISTER_CARD_FAIL'
export const USER_REGISTER_CARD_RESET = 'USER_REGISTER_CARD_FAIL'

export const USER_CHANGE_PIN_REQUEST = 'USER_CHANGE_PIN_REQUEST'
export const USER_CHANGE_PIN_SUCCESS = 'USER_CHANGE_PIN_SUCCESS'
export const USER_CHANGE_PIN_FAIL = 'USER_CHANGE_PIN_FAIL'
export const USER_CHANGE_PIN_RESET = 'USER_CHANGE_PIN_FAIL'



export const USER_VIEW_ALL_LOG_REQUEST = 'USER_VIEW_ALL_LOG_REQUEST'
export const USER_VIEW_ALL_LOG_SUCCESS = 'USER_VIEW_ALL_LOG_SUCCESS'
export const USER_VIEW_ALL_LOG_FAIL = 'USER_VIEW_ALL_LOG_FAIL'